INSERT INTO park_spaces(is_available, parking_space_name, vehicle_id)
VALUES (TRUE , 'AX01', 1),
       (TRUE , 'AX02', 1),
       (TRUE , 'AX03', 1),
       (TRUE , 'AX04', 1),
       (TRUE , 'AX05', 1),
       (TRUE , 'BX01', 2),
       (TRUE , 'BX02', 2),
       (TRUE , 'BX03', 2),
       (TRUE , 'BX04', 2),
       (TRUE , 'BX05', 2),
       (TRUE , 'BX06', 2),
       (TRUE , 'BX07', 2),
       (TRUE , 'BX08', 2),
       (TRUE , 'BX09', 2),
       (TRUE , 'BX10', 2),
       (TRUE , 'CX01', 3),
       (TRUE , 'CX02', 3);